[Work in progress] Translate docs to Russian
NYTimes/Store pull request #153
Opened 2017-03-08 22:28 UTC by maksim-m

Issue #145.

- [ ] Readme
- [ ] Data flow diagrams 
- [ ] Recipes

2017-03-08 22:32 UTC, digitalbuddha commented
Wow! I have the original sketch files if that helps with diagrams...

2017-03-08 23:00 UTC, maksim-m commented
Could you please upload it somewhere?

2017-03-08 23:00 UTC, digitalbuddha commented
Yup yup. Will do at some point tonight.

2017-03-08 23:04 UTC, digitalbuddha commented
Working in finding someone to review this....

2017-03-08 23:30 UTC, DAlexIV commented
@digitalbuddha Hi! I'm native Russian speaker too, so I can review this PR

2017-03-08 23:39 UTC, digitalbuddha commented
Fantastic thank you kindly

2017-03-09 01:23 UTC, vrfloppa requested changes
@maksim-m Reviewed your readme draft
Yup, there is some typos and untranslated peaces, nevertheless, well done, continue in the same spirit
Some peaces of text in Russian were even more clear to me than the English version :)

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +И для социальных, и для новостных, и для business-to-business приложений, пользователи ожидают удобное взаимодействие как при подключении к сети, так и в автономном режиме.
Тут скорее не удобное, а именно бесшовное

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Store похож на паттерн «репозиторий» [[https://msdn.microsoft.com/en-us/library/ff649690.aspx](https://msdn.microsoft.com/en-us/library/ff649690.aspx)], предоставляющий реактивный API, реализованный
потерял конец предложения "которая придерживается однонаправленного потока данных"

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Store возвращает данные в виде `Observable`, обеспечивая удобную работу с тредами.
потоками? :)

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Созданный Store управляет логикой обработки потока данных, позволяя вашему представлению использовать наиболее подходящий источник данных, и гарантирует, что новейшие данные будут доступны для послед
можно перевести views просто как вьюхи, а можно и как представление (сложно хороший перевод найти)

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> ++ кэш на диске для использования в автономном режиме
кэш с большой буквы :)

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> ++ Удобный API для запроса данных: получение кэшированных/новых данных или подписка на их будущие обновления.
Я бы перевел rich если не как богатый, то как многофункциональный в данном случае)

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Для создания Store используется builder (строитель).
мне кажется, лучше либо вообще без уточнения, либо так - (паттерн строитель)

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Store исползует универсальные ключи в качестве идентификаторов для данных.
мне кажется, тут имелось ввиду именно про дженерики, поэтому может лучше "типизированные ключи"?

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Это позволяет предотвратить загрузку свежих данных из сети (или другого внешнего источника), чтобы уменьшить расход трафика и заряда батареи.
и заряд

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Хороший вариант использования: пересоздание представления (activity или fragment) после поворота устройства — будут загружены кэшированные данные из Store.
может лучше "Хороший пример использования"? Хороший вариант использования как-то режет слух

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Использование Store поможет вам избежать необходимости реализовывать эту логику на уровне представления.
Вроде бы в оригинале "Having this data available can help you ...", я бы перевел как "Использование этих данных поможет вам..."

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Методы `fetch()` и `get()` одно значение и затем вызывает `onCompleted()` или выбрасывает исключение в случае ошибки.
пропустил emit (например порождают)

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Для обновлений в реальном времени вы также можете вызвать метод `store.stream()`, который возвращает `Observable`, который производит эмиссию при сохранении нового объекта в Store.
производит эмиссию, лол)
вот в этой классической серии статей на хабре https://habrahabr.ru/post/265269/ emit переводят как порождает, предлагаю придержаться той же стратегии)
поэтому здесь должно быть что-то вроде "порождает элемент"

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Используйте оператор RxJava `filter()`, чтобы подписаться только на определенные события.
В оригинале "Вы можете использовать"

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Store предлагает дополнительные механизмы для предотвращения дублирующих запросов одних и тех же данных.
либо уж дублирующих друг друга, либо дублирующихся

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Это полезно в ситуациях, когда вашему приложению требуется сделать много асинхронных вызовов для одних и тех же данных или когда пользователь интенсивно запрашивает обновление данных.
пропустил at startup - на старте приложения

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Обновленный поток данных будет выглядеть следующим образом:
Не хватает слова "Теперь", тут же наверное суть в итеративном усложении механизма кэширования, поэтому наверное имеет смысл подчеркивать настоящее время

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Отдельный артефакт предоставляет парсеры, использующие Gson, которые могут быть полезны, если `Fethcer` возвращает Reader, BufferedSource или String:
There are also separate middleware libraries with parsers наверное лучше перевести как "Так же существуют отдельные промежуточные библиотеки с парсерами "
и еще в конце надо уточнить, что парсер именно Gson

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Можно кэширование данных на диске, использую экземпляр класса `Persister` при создании Store.
Можно включить кэширование
ИспользуЯ

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Всякий раз, после выполнения сетевого запроса Store будет сохранять данные на диск, а затем считывать их.
по-моему, запятая после всякий раз не нужна

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Поток данных будет выглядеть так:
Теперь поток данных будет выглядеть так

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Единственное требование заключается в том, что данные должны быть одного и того же типа при сохранении/получение, что и возвращаемое функцией Fetcher значение.
получении

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Технически, ничто не мешает вам реализовать с помощью класса `Persister` кэш в памяти (а не на диске), чтобы вместо двух слоёв кэша иметь один: с данными в оригинальном формате и уже распарсенными, ч
По-моему тут получилось даже понятнее, чем в оригинале 👍

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Это позволяет функции получения данных работать непосредственно с сетевым потоком.
скорее функции сохранения данных)

2017-03-09 01:23 UTC, vrfloppa commented on docs/ru/README.md
> +Мы установили, что наибольшей скорости сохранения на диск можно добиться, выполняя потоковое сохранени данных из сети.
сохранение
из сети прямо на диск

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> +### Ограничение частоты обновлений
В саммари ты перевел это как "Оптимизация запросов", мне кажется, этот вариант круче)

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> ++ Кэшировании в памяти с помощью Guava Cache
кэширование

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> ++ Возможность подписаться на все новые эмиссии из сети (метод `stream()`)
мне кажется лучше "элементы" (которые порождаются)

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> +Благодаря передачи данных из сети на диск и с диска в парсер в формате потока байт, `SourcePersister` потребляет малое количество памяти.
передаче

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> +Это позволяет нам загружать множество ответов в формате json размером более 1mb  и не беспокоиться об исплючениях OutOfMemory на устройствах с малым объемом памяти.
исключениях
dozens of repsonses - десятки ответов

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> +После этого, вы можете настроить работу Store один из двух способов:
одним из

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> +The user will still get the stale record returned to them.
доперевести надо бы

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> +`networkBeforeStale` - Store will try to get network source when disk data is stale.
и тут тоже

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> ++ **Store** Содержит только классы Store, зависит от RxJava и фртефакта кэша
артефакта

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> ++ **File System** Persistence Library built using OKIO Source/Sink + Middleware for streaming from Network to FileSystem
доперевести

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> +Кроме того, вики этого репозитория некоторые рецепты для распространненых сценариев использования
в вики этого репозитория есть

2017-03-09 01:23 UTC, DAlexIV commented on docs/ru/README.md
> +Поток данных, которым управляет Store, будет выглядеть следующим образом:
Пропустил So far :) Можно перевести как "На данный момент" например

2017-03-09 02:45 UTC, vohsalab commented on docs/ru/README.md
> +Store похож на паттерн «репозиторий» [[https://msdn.microsoft.com/en-us/library/ff649690.aspx](https://msdn.microsoft.com/en-us/library/ff649690.aspx)], предоставляющий реактивный API, реализованный
Вообще я бы предложение построил по-другому, а то сейчас получается что API предоставляет сам паттерн.
Что-нибудь типа "Store похож на паттерн «репозиторий» [[https://msdn.microsoft.com/en-us/library/ff649690.aspx](https://msdn.microsoft.com/en-us/library/ff649690.aspx)], вдобавок предоставляя реактивный API, реализованный с помощью RxJava, который придерживается однонаправленного потока данных"

2017-03-09 02:47 UTC, vohsalab commented on docs/ru/README.md
> +Когда вы создаёте новую реализацию Store, вы предоставляете ему `Fetcher` — функцию, которая определяет, как будет происходить загрузка данных из интернета.
может быть заменить "интернет" на более обобщенное? "из сети" или "через сеть"

2017-03-09 02:51 UTC, vohsalab commented on docs/ru/README.md
> +Созданный Store управляет логикой обработки потока данных, позволяя вашему представлению использовать наиболее подходящий источник данных, и гарантирует, что новейшие данные будут доступны для послед
"позволяя элементам пользовательского интерфейса использовать их наиболее подходящий источник"

2017-03-09 02:52 UTC, vohsalab commented on docs/ru/README.md
> +Используя Store, с помощью двух слоёв кэширования (память и диск), вы исключите ситуации, когда один и тот же сетевой запрос будет выполняться избыточное количество раз.
лучше "уровни кэширования" наверное

2017-03-09 02:52 UTC, vohsalab commented on docs/ru/README.md
> +Далее последуют более простые примеры, демонстрирующие каждую деталь в отдельности.
"После этого" вместо "Далее"

2017-03-09 02:54 UTC, vohsalab commented on docs/ru/README.md
> +Store исползует универсальные ключи в качестве идентификаторов для данных.
мягкий знак пропустит в слове "использует"

2017-03-09 02:55 UTC, vohsalab commented on docs/ru/README.md
> +Это позволяет предотвратить загрузку свежих данных из сети (или другого внешнего источника), чтобы уменьшить расход трафика и заряда батареи.
тогда получается "чтобы уменьшить...заряд батареи" :)

2017-03-09 03:00 UTC, vohsalab commented on docs/ru/README.md
> +Использование Store поможет вам избежать необходимости реализовывать эту логику на уровне представления.
Только не использование, а "Доступность"

2017-03-09 03:02 UTC, vohsalab commented on docs/ru/README.md
> +Методы `fetch()` и `get()` одно значение и затем вызывает `onCompleted()` или выбрасывает исключение в случае ошибки.
"вызывают" и "выбрасывают". Множественное число

2017-03-09 03:07 UTC, vohsalab commented on docs/ru/README.md
> +Для обновлений в реальном времени вы также можете вызвать метод `store.stream()`, который возвращает `Observable`, который производит эмиссию при сохранении нового объекта в Store.
Ну можно сказать "отправляет сообщение каждый раз, когда новый объект сохраняется в Store"

2017-03-09 03:08 UTC, vohsalab commented on docs/ru/README.md
> +Для обновлений в реальном времени вы также можете вызвать метод `store.stream()`, который возвращает `Observable`, который производит эмиссию при сохранении нового объекта в Store.
ну или "порождает событие"

2017-03-09 03:13 UTC, vohsalab commented on docs/ru/README.md
> +Аналогичным образом есть артефакты парсеров для Moshi и Jackson!
"Аналогичным образом есть" по-русски не очень звучит. Лучше "Так же существуют"

2017-03-09 03:15 UTC, vohsalab commented on docs/ru/README.md
> +Лучше, если данные будут передаваться из сети на диск с использованием BufferedSource или Reader в качестве типа данных (а не String).
"Идеальным вариантом будет, если..."

2017-03-09 03:25 UTC, vohsalab commented on docs/ru/README.md
> +Технически, ничто не мешает вам реализовать с помощью класса `Persister` кэш в памяти (а не на диске), чтобы вместо двух слоёв кэша иметь один: с данными в оригинальном формате и уже распарсенными, ч
Может и понятнее, но совсем неправильно :)
"Теоретически, ничто не мешает вам реализовать свою версию класса `Persister`, который для кэширования данных будет использовать только память устройства. В таком случае в памяти будут храниться не один а два уровня кэша: первый с оригинальными данными, а второй с распарсенными, что позволит делиться кэшем `Persister` между разными экземплярами Store"

2017-03-09 03:27 UTC, vohsalab commented on docs/ru/README.md
> +Это позволяет функции получения данных работать непосредственно с сетевым потоком.
там в оригинале про объект Persister говорится, какие функции вообще?

2017-03-09 03:28 UTC, vohsalab commented on docs/ru/README.md
> +Мы установили, что наибольшей скорости сохранения на диск можно добиться, выполняя потоковое сохранени данных из сети.
тогда в первой части предложения "на диск" надо убрать

2017-03-09 03:28 UTC, vohsalab commented on docs/ru/README.md
> +Поэтому мы включили отдельный артефакт с библиотекой, предлагающей реактивную файловую систему, использующую `BufferedSource` из библиоткеи Okio.
почему не просто библиотеку?

2017-03-09 03:29 UTC, vohsalab commented on docs/ru/README.md
> +Поэтому мы включили отдельный артефакт с библиотекой, предлагающей реактивную файловую систему, использующую `BufferedSource` из библиоткеи Okio.
"библиоткеи" -> "библиотеки"

2017-03-09 03:34 UTC, vohsalab commented on docs/ru/README.md
> ++ Возможность переподписки после очистки кэша (метод `getRefreshing()`. Полезно, если нужно выполнить запрос типа POST, после чего обновить экран)
Возможность получить уведомление об очистке кэша, а так же переподписаться после этого
"обновить экран" -> "обновить другой экран"

2017-03-09 03:35 UTC, vohsalab commented on docs/ru/README.md
> +Благодаря передачи данных из сети на диск и с диска в парсер в формате потока байт, `SourcePersister` потребляет малое количество памяти.
"потока байтов"

2017-03-09 03:36 UTC, vohsalab commented on docs/ru/README.md
> +Как упоминалось выше, использование Store позволяет нам делать такие вещи, как вызов `configStore.get()` множествно раз асинхронно, прежде чем наша MainActivity закончит загрузку, не блокируя основно
"множествно" -> "множество"

2017-03-09 03:36 UTC, vohsalab commented on docs/ru/README.md
> +Как упоминалось выше, использование Store позволяет нам делать такие вещи, как вызов `configStore.get()` множествно раз асинхронно, прежде чем наша MainActivity закончит загрузку, не блокируя основно
и не загружая сеть

2017-03-09 03:37 UTC, vohsalab commented on docs/ru/README.md
> +If the network source throws an error or is empty, stale disk data will be returned.
ну и тут вестимо

2017-03-09 03:39 UTC, vohsalab commented on docs/ru/README.md
> +`networkBeforeStale` - Store will try to get network source when disk data is stale.
"Store попытается использовать сетевой источник, если данные устарели"

2017-03-09 03:41 UTC, vohsalab commented on docs/ru/README.md
> +The user will still get the stale record returned to them.
`refreshOnStale` инвалидирует дисковый кэш, каждый раз когда данные устареют. Пользователь получит устаревшие данные

2017-03-09 03:43 UTC, vohsalab commented on docs/ru/README.md
> +Примечание: релизы синхронизированны с состоянием ветки master (а не develop)
синхронизированы

2017-03-09 03:45 UTC, vohsalab commented on docs/ru/README.md
> ++ **File System** Persistence Library built using OKIO Source/Sink + Middleware for streaming from Network to FileSystem
**File System** библиотека, использующая OKIO Source/Sink + Middleware для создания потока данных из сети на файловую систему

2017-03-09 03:47 UTC, vohsalab commented on docs/ru/README.md
> +Кроме того, вики этого репозитория некоторые рецепты для распространненых сценариев использования
или "Вики этого репозитория содержит наборы рецептов для.."
"распространненых" -> "распространенных"

2017-03-09 07:56 UTC, DAlexIV commented on docs/ru/README.md
> +Созданный Store управляет логикой обработки потока данных, позволяя вашему представлению использовать наиболее подходящий источник данных, и гарантирует, что новейшие данные будут доступны для послед
о, да, можно как и "элементы пользовательского интерфейса"

2017-03-09 07:56 UTC, DAlexIV commented on docs/ru/README.md
> +Это позволяет предотвратить загрузку свежих данных из сети (или другого внешнего источника), чтобы уменьшить расход трафика и заряда батареи.
ага

2017-03-09 07:57 UTC, DAlexIV commented on docs/ru/README.md
> +Использование Store поможет вам избежать необходимости реализовывать эту логику на уровне представления.
именно

2017-03-09 07:57 UTC, DAlexIV commented on docs/ru/README.md
> +Для обновлений в реальном времени вы также можете вызвать метод `store.stream()`, который возвращает `Observable`, который производит эмиссию при сохранении нового объекта в Store.
да, можно "порождает событие"

2017-03-09 15:14 UTC, AlexBonel commented on docs/ru/README.md
> +Далее последуют более простые примеры, демонстрирующие каждую деталь в отдельности.
"Затем"

Одно слово лучше двух :)

2017-03-09 15:22 UTC, DAlexIV commented on docs/ru/README.md
> +Технически, ничто не мешает вам реализовать с помощью класса `Persister` кэш в памяти (а не на диске), чтобы вместо двух слоёв кэша иметь один: с данными в оригинальном формате и уже распарсенными, ч
ну да, твое правильнее)

2017-03-09 15:23 UTC, DAlexIV commented on docs/ru/README.md
> +Это позволяет функции получения данных работать непосредственно с сетевым потоком.
кстати да

2017-03-09 15:23 UTC, DAlexIV commented on docs/ru/README.md
> +Мы установили, что наибольшей скорости сохранения на диск можно добиться, выполняя потоковое сохранени данных из сети.
+

2017-03-09 15:26 UTC, DAlexIV commented on docs/ru/README.md
> +Поэтому мы включили отдельный артефакт с библиотекой, предлагающей реактивную файловую систему, использующую `BufferedSource` из библиоткеи Okio.
да, тоже не очень понял зачем вообще тут артефакты появились

2017-03-09 15:33 UTC, AlexBonel commented on docs/ru/README.md
> +Хороший вариант использования: пересоздание представления (activity или fragment) после поворота устройства — будут загружены кэшированные данные из Store.
не лучше ли "UI" использовать вместо "представления"?

2017-03-09 21:59 UTC, maksim-m commented
Thanks for the feedback! I updated the file.

2017-03-09 23:19 UTC, vrfloppa requested changes
Thanks for your update, but there is still a couple of odd typos

2017-03-09 23:19 UTC, DAlexIV commented on docs/ru/README.md
> +Поэтому мы включили отдельную библиотеку, предлагающею реактивную файловую систему, использующую `BufferedSource` из библиотеки Okio.
предлагающую

2017-03-09 23:19 UTC, DAlexIV commented on docs/ru/README.md
> ++ **File System** библиотека, использующая Okio Source/Sink + Middleware для сохранения потока данных из сети на файловую систему
может в файловую систему?)

2017-03-09 23:33 UTC, maksim-m commented
Typos fixed.

2017-03-09 23:45 UTC, vrfloppa approved these changes
Cool!

2017-03-10 19:32 UTC, vohsalab commented on docs/ru/README.md
> +Методы `fetch()` и `get()` порождают одно значение и затем вызывает `onCompleted()` или выбрасывает исключение в случае ошибки.
Тут везде нужно множественное число: методы...порождают...вызывают...выбрасывают

2017-03-13 18:14 UTC, vohsalab commented on docs/ru/README.md
> +Это может быть поелзно, если вы хотите внедрить зависимость Store или добавить несколько вспомогательных методов:
поелзно -> полезно

2017-03-14 14:52 UTC, vohsalab commented on docs/ru/README.md
> +Это может быть поелзно, если вы хотите внедрить зависимость Store или добавить несколько вспомогательных методов:
@maksim-m пофиксишь эту опечатку и я заапрувлю пулл реквест :)

2017-03-14 14:53 UTC, vohsalab commented on docs/ru/README.md
> +Методы `fetch()` и `get()` порождают одно значение и затем вызывает `onCompleted()` или выбрасывает исключение в случае ошибки.
и тут единственное число на множественное не исправил

2017-03-14 21:25 UTC, maksim-m commented on docs/ru/README.md
> +Это может быть поелзно, если вы хотите внедрить зависимость Store или добавить несколько вспомогательных методов:
Done.

2017-03-15 20:50 UTC, digitalbuddha commented
Once we get 1 more 👍we will do a pass over internally before merging.

2017-03-15 22:37 UTC, sergei-zh commented on docs/ru/README.md
> +И для социальных, и для новостных, и для business-to-business приложений, пользователи ожидают бесшовное взаимодействие как при подключении к сети, так и в автономном режиме.
Wrong grammatical case - бесшовное --> бесшовного

2017-03-15 22:50 UTC, sergei-zh commented on docs/ru/README.md
> +Это позволяет предотвратить загрузку свежих данных из сети (или другого внешнего источника), чтобы уменьшить расход трафика и заряда батареи.
'чтобы уменьшить расход трафика и экономить заряд батареи' ?

2017-03-15 22:58 UTC, sergei-zh commented on docs/ru/README.md
> +Директория app содержит тестовое приложение, демонстирующее использование Store.
демонстирующее -> демонстрирующее

2017-03-15 22:58 UTC, sergei-zh commented on docs/ru/README.md
> +Кроме того, вики этого репозитория содержит некоторые рецепты для распространенных сценариев использования
It s better to put a column to the end f this sentence:
 использования:

2017-03-16 00:06 UTC, sergei-zh commented on docs/ru/README.md
> +
удобная --> легкая в использовании (?)

2017-03-16 00:09 UTC, sergei-zh commented on docs/ru/README.md
> ++ Современные Android-приложения нуждаются в удобном и всегда доступном представлении данных.
Современные Android-приложения нуждаются в удобном и надежном способе доступа к данным. (?)

2017-03-16 00:11 UTC, sergei-zh commented on docs/ru/README.md
> +И для социальных, и для новостных, и для business-to-business приложений, пользователи ожидают бесшовное взаимодействие как при подключении к сети, так и в автономном режиме.
Wrong preposition: И  от социальных, и от новостных, и от business-to-business приложений пользователи ожидают ...

2017-03-16 00:12 UTC, sergei-zh commented on docs/ru/README.md
> ++ В международном роуминге большой объем загружаемых данных может привести к астрономическим счетам за связь.
астрономическим счетам -- too informal

2017-03-16 00:16 UTC, sergei-zh commented on docs/ru/README.md
> +Store похож на паттерн «репозиторий» [[https://msdn.microsoft.com/en-us/library/ff649690.aspx](https://msdn.microsoft.com/en-us/library/ff649690.aspx)], вдобавок предоставляя реактивный API, реализов
похож на паттерн --> имеет в основе паттерн / основан на паттерне (?)

вдобавок (too informal) --> в дополнение




 который придерживается однонаправленного потока данных

2017-03-16 00:17 UTC, sergei-zh commented on docs/ru/README.md
> +Store обеспечивает уровень абстракции между элементами UI и операциями с данными.
уровень / слой (?)

2017-03-16 00:20 UTC, sergei-zh commented on docs/ru/README.md
> +Store отвечает за управление загрузкой конкретного запроса данных.
Store отвечает за управление конкретным запросом к данным. (?)

2017-03-16 00:21 UTC, sergei-zh commented on docs/ru/README.md
> +Также вы можете настроить, как Store будет кэшировать данные в памяти и на диске, а так же то, как будет происходить их парсинг.
как -> способ которым Store будет ..... (?)

2017-03-16 00:22 UTC, sergei-zh commented on docs/ru/README.md
> +Созданный Store управляет логикой обработки потока данных, позволяя элементам пользовательского интерфейса использовать их наиболее подходящий источник, и гарантирует, что новейшие данные будут досту
использовать их наиболее подходящий источник --> использовать наиболее подходящий  их источник

2017-03-16 03:40 UTC, sergei-zh commented on docs/ru/README.md
> +Для начала посмотрим, как выглядит полностью сконфигурированный Store.
посмотрим --> рассмотрим

2017-03-16 03:42 UTC, sergei-zh commented on docs/ru/README.md
> +Затем последуют более простые примеры, демонстрирующие каждую деталь в отдельности.
Затем обратимся к более простым примерам, демонстрирующим каждую деталь в отдельности. (?)

2017-03-16 03:45 UTC, sergei-zh commented on docs/ru/README.md
> +С учетом указанной выше конфигурации вы получите:
С учетом указанной --> используя указанную

2017-03-16 03:47 UTC, sergei-zh commented on docs/ru/README.md
> ++ Парсинг через потоковый API, чтобы ограничить использование памяти
чтобы ограничить использование --> для ограничения использования

2017-03-16 03:49 UTC, sergei-zh commented on docs/ru/README.md
> +Аналогичным образом, ключ будет использоваться в качестве основного идентификатора в кэше (Убедитесь, что ваш ключ правильно реализует `hashCode()`!)
(Убедитесь --> (убедитесь

2017-03-16 03:52 UTC, sergei-zh commented on docs/ru/README.md
> +Для удобства мы включили нашу собственную реализацию ключа, называемую BarCode (штрихкод).
мы включили в библиотеку нашу собственную реализацию ключа

2017-03-16 03:54 UTC, sergei-zh commented on docs/ru/README.md
> +По умолчанию, 100 элементов будут сохранены в памяти 24 часа.
сохранены в памяти на 24 часа.

2017-03-16 15:47 UTC, vohsalab commented on docs/ru/README.md
> ++ В международном роуминге большой объем загружаемых данных может привести к астрономическим счетам за связь.
@sergei-zh В оригинале так же

2017-03-16 15:50 UTC, vohsalab commented on docs/ru/README.md
> +Также вы можете настроить, как Store будет кэшировать данные в памяти и на диске, а так же то, как будет происходить их парсинг.
оба варианта имеют право на существование. Не могу это назвать ошибкой перевода

2017-03-16 15:51 UTC, vohsalab commented on docs/ru/README.md
> +Затем последуют более простые примеры, демонстрирующие каждую деталь в отдельности.
обе версии равнозначны? по моему мнению можно не исправлять

2017-03-16 15:53 UTC, vohsalab commented on docs/ru/README.md
> ++ Парсинг через потоковый API, чтобы ограничить использование памяти
опять же равнозначно

2017-03-20 11:32 UTC, digitalbuddha commented
I wanted to merge this today unless objections. We can open prs for changes. Thank you everyone!

2017-03-21 14:28 UTC, vohsalab approved these changes
Nicely done!

2017-03-21 14:31 UTC, merged

2017-03-21 14:32 UTC, digitalbuddha commented
Fantastic job! thank you all