Return object with meta data
NYTimes/Store pull request #250
Opened 2017-07-21 14:19 UTC by charbgr

Hey,

this is an attempt to return an object with meta data.

I introduced a Result model which returns the parsed object accompanied by its source(network/cache). I couldn't distinguish if the cache is from memory or disk due to the fact that memory works as an "interceptor".

Let me know what you think.

2017-07-21 14:34 UTC, digitalbuddha commented
closes https://github.com/NYTimes/Store/issues/226

2017-07-21 14:34 UTC, digitalbuddha commented on build.gradle
> +//    project.plugins.apply('net.ltgt.errorprone')
?

2017-07-21 14:36 UTC, digitalbuddha commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +    public String getSource() {
remove get from name pls (unless there is also a set)

2017-07-21 14:37 UTC, pavlospt commented on build.gradle
> +//    project.plugins.apply('net.ltgt.errorprone')
@digitalbuddha That's probably a mistake, since the project wouldn't run with error-prone enabled.

2017-07-21 14:54 UTC, charbgr commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +    public String getSource() {
Done! :)

2017-07-21 15:21 UTC, charbgr commented on build.gradle
> +//    project.plugins.apply('net.ltgt.errorprone')
I rebased it and remove the comments. Sorry for the confusion!

2017-07-24 14:43 UTC, wdziemia requested changes

2017-07-24 14:43 UTC, wdziemia commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +        if (source == null) {
if `this.source` is null and o.source is not null, return that they are equal?

2017-07-24 14:43 UTC, wdziemia commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +        if (value == null) {
if `this.value` is null and o.value is not null, return that they are equal?

2017-07-24 14:43 UTC, wdziemia commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +        } else {
can be simplified to `else { return value.equals(result.value) }`

2017-07-24 14:43 UTC, wdziemia commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +            if (!source.equals(result.source)) {
can be simplified to `else { source value.equals(source.value) }`

2017-07-24 15:30 UTC, charbgr commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +            if (!source.equals(result.source)) {
@wdziemia what do you mean by `else { *source* value.equals(source.value) }`

2017-07-24 15:31 UTC, wdziemia commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +            if (!source.equals(result.source)) {
@charbgr whoops, edited the original

2017-07-24 17:54 UTC, cybo42 commented
(nitpick) remove the `.DS_Store` and `app/.DS_Store` files from the PR

2017-07-24 18:00 UTC, cybo42 commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +
Any thoughts on using an Enum to identify source, something like below?
```
   public static enum Source {
        DISK, NETWORK
    }
```

2017-07-24 18:15 UTC, charbgr commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +
@cybo42 I am ok with that! I didn't do it cause of the increase of DEX files.

2017-07-24 18:27 UTC, charbgr commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +        if (value == null) {
Fixed

2017-07-24 18:27 UTC, charbgr commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +        } else {
Fixed

2017-07-24 18:27 UTC, charbgr commented on store/src/main/java/com/nytimes/android/external/store/util/Result.java
> +
Done

2017-07-24 20:40 UTC, digitalbuddha commented
lgtm

2017-07-24 21:10 UTC, cybo42 approved these changes

2017-07-25 21:31 UTC, merged

2017-07-25 21:31 UTC, digitalbuddha commented
Thank you for contribution! Snapshot will be live in twenty minutes. We will make a store 3.0 release this week.