Added ParsingFetcher that wraps a Raw type Parser and and Raw type Fetcher
NYTimes/Store pull request #279
Opened 2017-10-20 13:45 UTC by magillus

Reading and parsing network/file fetch can be done at same step with single Fetcher.

2017-10-20 13:47 UTC, magillus commented
Enhancement from the `issue` #275

2017-10-20 16:28 UTC, stoyicker commented
note to self: if this is merged, add to kotlin artifact

2017-10-23 01:39 UTC, digitalbuddha commented on store/src/main/java/com/nytimes/android/external/store/base/impl/ParsingFetcher.java
> +     * Returns parsing fetcher for fetcher and parser
This comment seems odd, collapse it to just the sentence and remove the auto gen parameter comments.

2017-10-23 14:41 UTC, brianPlummer approved these changes

2017-10-23 17:49 UTC, ramonaharrison requested changes
The `develop` branch is deprecated, we're not planning any future Store releases from this branch. Please rebase off of `feature/rx2` and update to return an RxJava2 `io.reactivex.Single`.

Otherwise, LGTM. Thanks!

2017-10-23 17:49 UTC, ramonaharrison commented on store/src/main/java/com/nytimes/android/external/store/base/impl/ParsingFetcher.java
> +    public Observable<Parsed> fetch(@Nonnull Key key) {
Should be based off of the `feature/rx2` branch and return a `io.reactivex.Single`

2017-10-23 18:33 UTC, magillus commented
I will close this PR because of different branch from my fork.

2017-10-23 18:33 UTC, closed without merging

2017-10-23 18:34 UTC, pavlospt commented
@magillus You can rebase it on `feature/rx2` instead of closing it.

2017-10-23 18:43 UTC, magillus commented
There were some merge conflicts etc. my PR is simple adding a file and unit test so was faster just create branch from `feature/rx2`