Fix memory policy default size
NYTimes/Store pull request #328
Opened 2018-03-29 14:24 UTC by pavlospt

I added a condition to return `maxSize=1` only if no `maxSize` set.

2018-04-10 07:57 UTC, pavlospt commented
Any updates on this 😃 ?

2018-04-30 13:48 UTC, tiwiz requested changes

2018-04-30 13:48 UTC, tiwiz commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:3.1.0'
Could we move it to 3.1.2, please?

2018-05-13 19:36 UTC, pavlospt commented
@tiwiz I bumped the AGP version. Sorry for taking so long. Somehow I missed your comment's notification! :/

2018-05-13 21:34 UTC, tiwiz commented
@pavlospt thank you! Let's wait for one more reviewer to approve and then we can merge it! Thanks!

2018-05-13 21:55 UTC, digitalbuddha approved these changes

2018-05-13 21:57 UTC, tiwiz approved these changes

2018-05-13 21:57 UTC, merged