Fixes errors in README
NYTimes/Store pull request #336
Opened 2018-04-29 20:48 UTC by KevCron

Let me know if this is the wrong base branch to be merging into.

2018-04-30 13:26 UTC, ramonaharrison commented on README.md
> +Since it is rare for data to arrive from the network in the format that your views need, Stores can delegate to a parser by using a `StoreBuilder.<BarCode, BufferedSource, Article>parsedWithKey()``1
Is the ``1 a typo here?

2018-04-30 13:29 UTC, tiwiz requested changes

2018-04-30 13:29 UTC, tiwiz commented on README.md
> +Since it is rare for data to arrive from the network in the format that your views need, Stores can delegate to a parser by using a `StoreBuilder.<BarCode, BufferedSource, Article>parsedWithKey()``1
The final `1 looks a bit off, could it be a typo?

2018-05-01 16:07 UTC, KevCron commented
Removed the typo, good catch!

2018-05-02 20:19 UTC, tiwiz approved these changes

2018-05-03 13:41 UTC, ramonaharrison commented on README.md
> +Since it is rare for data to arrive from the network in the format that your views need, Stores can delegate to a parser by using a `StoreBuilder.<BarCode, BufferedSource, Article>parsedWithKey()``
hate to nitpick,  but I think there's still an extra "`" that is messing up the formatting. otherwise, LGTM!

2018-06-05 01:13 UTC, KevCron commented
@ramonaharrison @tiwiz Can I merge this?

2018-06-05 01:14 UTC, digitalbuddha commented
Cc @wdziemia

2018-06-05 13:57 UTC, wdziemia approved these changes

2018-06-05 13:58 UTC, merged